/*
 * Copyright 2023 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(cfo_estimator.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(087c1278052be74e07fa4a45150b03ff)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/radar_dsp/cfo_estimator.h>
// pydoc.h is automatically generated in the build directory
#include <cfo_estimator_pydoc.h>

void bind_cfo_estimator(py::module& m)
{

    using cfo_estimator    = gr::radar_dsp::cfo_estimator;


    py::class_<cfo_estimator, gr::block, gr::basic_block,
        std::shared_ptr<cfo_estimator>>(m, "cfo_estimator", D(cfo_estimator))

        .def(py::init(&cfo_estimator::make),
           py::arg("training_seq_len"),
           py::arg("samp_rate"),
           D(cfo_estimator,make)
        )
        



        ;




}








