/*
 * Copyright 2023 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(energy_trigger.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(208d55c9ec3b781fb6ed7a7402160650)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/radar_dsp/energy_trigger.h>
// pydoc.h is automatically generated in the build directory
#include <energy_trigger_pydoc.h>

void bind_energy_trigger(py::module& m)
{

    using energy_trigger    = gr::radar_dsp::energy_trigger;


    py::class_<energy_trigger, gr::block, gr::basic_block,
        std::shared_ptr<energy_trigger>>(m, "energy_trigger", D(energy_trigger))

        .def(py::init(&energy_trigger::make),
           D(energy_trigger,make)
        )
        



        ;




}








