/*
 * Copyright 2023 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(harmonic_retrieval.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(88de119bc8f43222118dcbad7167593a)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/radar_dsp/harmonic_retrieval.h>
// pydoc.h is automatically generated in the build directory
#include <harmonic_retrieval_pydoc.h>

void bind_harmonic_retrieval(py::module& m)
{

    using harmonic_retrieval    = gr::radar_dsp::harmonic_retrieval;


    py::class_<harmonic_retrieval, gr::block, gr::basic_block,
        std::shared_ptr<harmonic_retrieval>>(m, "harmonic_retrieval", D(harmonic_retrieval))

        .def(py::init(&harmonic_retrieval::make),
           py::arg("samp_rate"),
           py::arg("fft_size"),
           D(harmonic_retrieval,make)
        )
        



        ;




}








