/*
 * Copyright 2023 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(lls.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(b2ccb335eaf5fa6c2941356b088ca99c)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/radar_dsp/lls.h>
// pydoc.h is automatically generated in the build directory
#include <lls_pydoc.h>

void bind_lls(py::module& m)
{

    using lls    = gr::radar_dsp::lls;
	//py::class_<gr::block>(m, "gr::block");

    py::class_<lls, gr::block, gr::basic_block,
        std::shared_ptr<lls>>(m, "lls", D(lls))

        .def(py::init(&lls::make),
           D(lls,make)
        )
        



        ;




}








