/*
 * Copyright 2023 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(pulse_align.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(be6e8cb055d8371a486d8a2eda281e4e)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/radar_dsp/pulse_align.h>
// pydoc.h is automatically generated in the build directory
#include <pulse_align_pydoc.h>

void bind_pulse_align(py::module& m)
{

    using pulse_align = gr::radar_dsp::pulse_align;


    py::class_<pulse_align, gr::block, gr::basic_block, std::shared_ptr<pulse_align>>(
        m, "pulse_align", D(pulse_align))

        .def(py::init(&pulse_align::make),
             py::arg("input_buffer_len"),
             py::arg("samp_rate"),
             py::arg("samps_per_sym"),
             D(pulse_align, make))


        ;
}
